FROM golang:1.22.5-alpine

# Update and install required packages
RUN apk update && apk upgrade && apk add curl

# Download kubectl binary
RUN curl -LO https://github.com/kubernetes/kubernetes/releases/latest/download/kubectl-linux-amd64

# Make it executable and move it to /usr/local/bin as kubectl
RUN chmod +x kubectl-linux-amd64 && mv kubectl-linux-amd64 /usr/local/bin/kubectl

# Verify kubectl installation
RUN kubectl version --client