FROM ubuntu:latest

# Update and install required packages
RUN apt update -y && apt upgrade -y && apt install curl -y

# Download the latest stable release of kubectl from the official Kubernetes CDN
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

# Make it executable
RUN chmod +x kubectl

# Move kubectl to /usr/local/bin (system-wide directory in the PATH)
RUN mv ./kubectl /usr/local/bin/kubectl

# Verify kubectl installation
RUN kubectl version --client