FROM golang:1.22.5-alpine

# Update and install required packages
RUN apk update && apk upgrade && apk add curl

# Download the latest stable release of kubectl from the official Kubernetes CDN
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

# Make it executable
RUN chmod +x kubectl

# Move kubectl to /usr/local/bin
RUN mv kubectl /usr/local/bin/

# Verify kubectl installation
RUN kubectl version --client