apiVersion: v1
kind: Service
metadata:
  name: goback-server
  namespace: default
  labels:
    app.kubernetes.io/name: goback
spec:
  selector:
    app.kubernetes.io/name: goback
  ports:
  - port: 8000
    name: http
  type: LoadBalancer