basePath: /api/v1
info:
  contact: {}
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /hello/{name}:
    get:
      consumes:
      - application/json
      description: Return greeting with name
      parameters:
      - description: Name to greet
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Hello {name}
          schema:
            type: string
      summary: Hello with name
      tags:
      - example
swagger: "2.0"
